parameters:
  vmImageName: 'windows-latest'
  jobName: 'run_test_windows'
  jobDisplayName: 'Run test'

jobs:
  - job: '${{ parameters.jobName }}_net461'
    pool:
      vmImage: ${{ parameters.vmImageName }}
    displayName: ${{ parameters.jobDisplayName }} - net461
    condition: startsWith('${{ parameters.vmImageName }}', 'win')
    steps:
    - download: current
    - task: DotNetCoreCLI@2
      displayName: Tests on Windows - net461
      inputs:
        command: test
        projects: test/test.csproj
        nobuild: true
        arguments: --runtime net461 --collect:"Code Coverage"
        testRunTitle: Tests on Windows - net461

  - job: '${{ parameters.jobName }}_netcoreapp31'
    pool:
        vmImage: ${{ parameters.vmImageName }}
    displayName: ${{ parameters.jobDisplayName }} - netcoreapp3.1
    steps:
    - download: current
    - task: DotNetCoreCLI@2
      displayName: Tests on ${{parameters.vmImageName}} - netcoreapp3.1
      inputs:
        command: test
        projects: test/test.csproj
        nobuild: true
        arguments: --runtime netcoreapp3.1 --collect:"Code Coverage"
        testRunTitle: Tests on ${{parameters.vmImageName}}
