parameters:
  vmImageName: 'windows-latest'
  jobName: 'run_test_windows'
  jobDisplayName: 'Run test'

jobs:
  - job: '${{ parameters.jobName }}_net461'
    pool:
      vmImage: ${{ parameters.vmImageName }}
    displayName: ${{ parameters.jobDisplayName }} - net461
    condition: startsWith('${{ parameters.vmImageName }}', 'win')
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: '5.0.x'

    - download: current

     task: DotNetCoreCLI@2
      displayName: Tests on Windows - net461
      inputs:
        command: test
        projects: test/test.csproj
        nobuild: true
        arguments: --runtime net461 --collect:"XPlat Code Coverage"
        testRunTitle: Tests on Windows - net461

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: cobertura
        summaryFileLocation: $(Agent.TempDirectory)/**/coverage.cobertura.xml

  - job: '${{ parameters.jobName }}_net50'
    pool:
        vmImage: ${{ parameters.vmImageName }}
    displayName: ${{ parameters.jobDisplayName }} - net5.0
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: '5.0.x'

    - download: current

    - task: DotNetCoreCLI@2
      displayName: Tests on ${{parameters.vmImageName}} - net5.0
      inputs:
        command: test
        projects: test/test.csproj
        nobuild: true
        arguments: --runtime net5.0 --collect:"XPlat Code Coverage"
        testRunTitle: Tests on ${{parameters.vmImageName}}

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: cobertura
        summaryFileLocation: $(Agent.TempDirectory)/**/coverage.cobertura.xml
