name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
pr:
  branches:
    include:
    - master
    - release*

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: build_and_tet
  pool:
    vmImage: windows-latest
  displayName: Build Microsoft.PowerShell.Pager
  jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
      clean: true
    - pwsh: |
        $(Build.SourcesDirectory)/Pager/build.ps1 -Clean -Configuration 'Release'
      displayName: Build
    - publish: "$(Build.SourcesDirectory)/Pager/src/bin/release"
      artifact: out

- stage: Test
  displayName: Test Microsoft.PowerShell.Pager
  jobs:
  - template: template/runtest.yml
    parameters:
      vmImageName: windows-latest
      jobName: run_test_windows
      jobDisplayName: Run tests Windows

  - template: template/runtest.yml
    parameters:
      vmImageName: ubuntu-latest
      jobName: run_test_ubuntu
      jobDisplayName: Run tests Ubuntu

  - template: template/runtest.yml
    parameters:
      vmImageName: macos-latest
      jobName: run_test_macos
      jobDisplayName: Run tests macOS

- stage: Compliance
  displayName: Compliance Microsoft.PowerShell.Pager
  pool:
    vmImage: windows-latest
  jobs:
  - job: Compliance_Job
    steps:
    - checkout: self
    - checkout: ComplianceRepo
    - template: ci-compliance.yml@ComplianceRepo

